version: "3.9"
services:
  web:
    build: .
    ports:
      - "8080:3000"     # host 8080 → container 3000
    volumes:
      - ./data:/app/data
    environment:
      - NODE_ENV=production
    depends_on:
      - db              # web은 db가 먼저 실행되어야 함

  db:
    image: postgres:16
    environment:
      - POSTGRES_USER=appuser
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=mydb
    volumes:
      - dbdata:/var/lib/postgresql/data

volumes:
  dbdata:
